### ISSUE TITLE
Questions about data and code!

### ISSUE THREAD

**Issue by Timothy-105** [Research-and-Project/mmWave_radar_tracking#1]
谢谢您分享的源码，我有两个问题想请教一下：
1、您在报告里说是用威孚高科的4D毫米波雷达采集的数据，但我在市面上都没找到这款雷达，您能提供这款雷达的购买途径吗？
2、在复现您的源码，show bounding box 的时候出现以下错误，是matlab的版本问题吗，我用的是matlab2016b。
main_MOTracking>plotBoundingbox>plotcube(line 57)
hdl=cellfun(@patch,XYZ{1},XYZ{2},XYZ{3},...
错误使用cellfun,不支持matlab.graphics.primitive.Patch输出类型。请将‘UniformOutput'设置为false

**Comment by dawnlh** [comment]
1. 是仿真数据，我没有关注硬件和数据来源，只是简单的实现下算法
2. MATLAB 2018b上没有什么问题
