### ISSUE TITLE
data capture

### ISSUE THREAD

**Issue by javadsd** [Research-and-Project/mmWave_radar_tracking#6]
Hello, 
I want to run the code with my own data, but I did not understand how you saved your data. In the SOT scenario, there are 231 frames and the dimensions of the frames are different. Can you explain about capturing and saving this data?

**Comment by dawnlh** [comment]
There are 10 numbers in each row of the radar data, and their meanings are:
X,Y,Z,RANGE, AZIMUTH, ELEVATION,DOPPLER,POWER,POWER_VALUE,TIMESTAMP_MS

**Comment by javadsd** [comment]
How can I calculate these parameters using raw data? Is the code for this part available?

**Comment by dawnlh** [comment]
Sorry, I only focus on the tracking algorithm, and I have no background knowledge about the radar system. But for comercial radar devices, I think there shoule be available toolboxes or softwares from their companies.
